# Generated by Django 3.1 on 2020-08-25 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=41, null=True, verbose_name='Фамилие')),
                ('photo', models.ImageField(blank=True, default='profile/noavatar.png', null=True, upload_to='profile/', verbose_name='Фотография')),
                ('telephone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
